//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlankJournal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlanksEntities : DbContext
    {
        public BlanksEntities()
            : base("name=BlanksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BPJournalTable> BPJournalTable { get; set; }
        public virtual DbSet<FoldersTable> FoldersTable { get; set; }
        public virtual DbSet<TBPCommentsTable> TBPCommentsTable { get; set; }
        public virtual DbSet<TBPHistoryTable> TBPHistoryTable { get; set; }
        public virtual DbSet<TBPInfoTable> TBPInfoTable { get; set; }
        public virtual DbSet<UsersTable> UsersTable { get; set; }
    }
}
