//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlankJournal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataTable
    {
        public DataTable()
        {
            this.BPJournalTable = new HashSet<BPJournalTable>();
            this.BPJournalTable1 = new HashSet<BPJournalTable>();
            this.TBPCommentsTable = new HashSet<TBPCommentsTable>();
            this.TBPHistoryTable = new HashSet<TBPHistoryTable>();
            this.TBPHistoryTable1 = new HashSet<TBPHistoryTable>();
            this.TBPHistoryTable2 = new HashSet<TBPHistoryTable>();
            this.TBPHistoryTable3 = new HashSet<TBPHistoryTable>();
            this.TBPInfoTable = new HashSet<TBPInfoTable>();
            this.TBPInfoTable1 = new HashSet<TBPInfoTable>();
        }
    
        public string ID { get; set; }
        public byte[] Data { get; set; }
        public bool isPDF { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string Author { get; set; }
        public string FileInfo { get; set; }
    
        public virtual ICollection<BPJournalTable> BPJournalTable { get; set; }
        public virtual ICollection<BPJournalTable> BPJournalTable1 { get; set; }
        public virtual UsersTable UsersTable { get; set; }
        public virtual ICollection<TBPCommentsTable> TBPCommentsTable { get; set; }
        public virtual ICollection<TBPHistoryTable> TBPHistoryTable { get; set; }
        public virtual ICollection<TBPHistoryTable> TBPHistoryTable1 { get; set; }
        public virtual ICollection<TBPHistoryTable> TBPHistoryTable2 { get; set; }
        public virtual ICollection<TBPHistoryTable> TBPHistoryTable3 { get; set; }
        public virtual ICollection<TBPInfoTable> TBPInfoTable { get; set; }
        public virtual ICollection<TBPInfoTable> TBPInfoTable1 { get; set; }
    }
}
