//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlankJournal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBPHistoryTable
    {
        public int Id { get; set; }
        public string TBPNumber { get; set; }
        public int PrevPDFData { get; set; }
        public int PrevWordData { get; set; }
        public int NewPDFData { get; set; }
        public int NewWordData { get; set; }
        public string Author { get; set; }
    
        public virtual DataTable DataTable { get; set; }
        public virtual DataTable DataTable1 { get; set; }
        public virtual DataTable DataTable2 { get; set; }
        public virtual DataTable DataTable3 { get; set; }
        public virtual TBPInfoTable TBPInfoTable { get; set; }
        public virtual UsersTable UsersTable { get; set; }
    }
}
