//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlankJournal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBPInfoTable
    {
        public int ID { get; set; }
        public string Number { get; set; }
        public string Folder { get; set; }
        public string Name { get; set; }
        public string ObjectInfo { get; set; }
        public string DataPDF { get; set; }
        public string DataWord { get; set; }
        public bool isActive { get; set; }
        public bool canUseTBP { get; set; }
    
        public virtual DataTable DataTable { get; set; }
        public virtual DataTable DataTable1 { get; set; }
        public virtual FoldersTable FoldersTable { get; set; }
    }
}
