//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlankJournal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBPHistoryTable
    {
        public int Id { get; set; }
        public string TBPNumber { get; set; }
        public byte[] PrevPDFData { get; set; }
        public byte[] PrevWordData { get; set; }
        public byte[] NewPDFData { get; set; }
        public byte[] NewWordData { get; set; }
        public string Author { get; set; }
    
        public virtual TBPInfoTable TBPInfoTable { get; set; }
        public virtual UsersTable UsersTable { get; set; }
    }
}
