//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlankJournal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersTable
    {
        public UsersTable()
        {
            this.BPJournalTable = new HashSet<BPJournalTable>();
            this.TBPCommentsTable = new HashSet<TBPCommentsTable>();
            this.TBPCommentsTable1 = new HashSet<TBPCommentsTable>();
            this.TBPHistoryTable = new HashSet<TBPHistoryTable>();
        }
    
        public string Login { get; set; }
        public string Name { get; set; }
        public bool IsNOS { get; set; }
        public bool IsNSS { get; set; }
    
        public virtual ICollection<BPJournalTable> BPJournalTable { get; set; }
        public virtual ICollection<TBPCommentsTable> TBPCommentsTable { get; set; }
        public virtual ICollection<TBPCommentsTable> TBPCommentsTable1 { get; set; }
        public virtual ICollection<TBPHistoryTable> TBPHistoryTable { get; set; }
    }
}
